# Generated by Django 5.2.5 on 2025-09-01 23:54

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message1', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message 1')),
                ('is_message1_active', models.BooleanField(default=False, verbose_name='Show Message 1')),
                ('message1_color', models.CharField(choices=[('green', 'Success - Green'), ('blue', 'Info - Blue'), ('orange', 'Warning - Orange'), ('red', 'Error - Red')], default='green', max_length=10, verbose_name='Message 1 Color')),
                ('message2', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message 2')),
                ('is_message2_active', models.BooleanField(default=False, verbose_name='Show Message 2')),
                ('message2_color', models.CharField(choices=[('green', 'Success - Green'), ('blue', 'Info - Blue'), ('orange', 'Warning - Orange'), ('red', 'Error - Red')], default='orange', max_length=10, verbose_name='Message 2 Color')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cgpa', models.CharField(blank=True, max_length=100, null=True)),
                ('fees', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('skill_required', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('vacancy', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='downloadable_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('student_name', models.CharField(max_length=100, verbose_name='Name of the Student')),
                ('vtu_number', models.CharField(max_length=20, verbose_name='VTU Number')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number of the Student')),
                ('department', models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student')),
                ('industry_name', models.CharField(max_length=100, verbose_name='Name of the Industry')),
                ('industry_location', models.CharField(max_length=100, verbose_name='Location of the Industry')),
                ('domain_of_work', models.CharField(max_length=100, verbose_name='Domain of Work')),
                ('industry_category', models.CharField(max_length=100, verbose_name='Category the Industry')),
                ('referal_person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Referal Person')),
                ('referal_person_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of the Referal Person')),
                ('referal_person_phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number of the Referal Person')),
                ('referal_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email of the Referal Person')),
                ('industry_website', models.URLField(blank=True, null=True, verbose_name='Website Link of the Industry')),
                ('industry_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Industry Contact Email')),
                ('industry_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Industry Contact Phone')),
                ('stipend_provided', models.CharField(max_length=3, verbose_name='Any Stipend Provided from the Industry?')),
                ('stipend_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='If Yes, How much Stipend?')),
                ('fees_required', models.CharField(max_length=3, verbose_name='Is there any need to pay fees to acquire the Internship?')),
                ('fees_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='If yes, How much fees?')),
                ('application_approved', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Not Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='Application Approval Status')),
                ('approval_message', models.TextField(blank=True, null=True, verbose_name='Message Regarding Approval Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('report_status', models.CharField(choices=[('REPORTED', 'Reported to the Company'), ('NOT_REPORTED', 'Not Reported to the Company'), ('PENDING', 'repoting on 21 july')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.CharField(blank=True, max_length=20, null=True)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_letter', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('approval_letter_got', models.BooleanField(default=False)),
                ('undertaking_letter', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('undertaking_letter_got', models.BooleanField(default=False)),
                ('bonafide_letter', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('bonafide_letter_got', models.BooleanField(default=False)),
                ('applied_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.company')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtu_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.student')),
            ],
            options={
                'unique_together': {('student', 'company', 'date')},
            },
        ),
    ]
