# Generated by Django 5.2.5 on 2025-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='active_approval_letter',
            field=models.BooleanField(default=True, verbose_name='Allow Internship Applications'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_bonafide_letter',
            field=models.BooleanField(default=True, verbose_name='Allow Bonafide Letter Uploads'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_file_upload',
            field=models.BooleanField(default=True, verbose_name='Allow File Uploads'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_undertaking_letter',
            field=models.BooleanField(default=True, verbose_name='Allow Undertaking Letter Uploads'),
        ),
    ]
