# Generated by Django 5.2.5 on 2025-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_sitesetting_active_approval_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='active_file_upload',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='active_approval_letter',
            field=models.BooleanField(default=True, verbose_name='Allow Approval Letter Uploads'),
        ),
    ]
