# Generated by Django 5.2.5 on 2025-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_remove_sitesetting_active_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_10',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_6',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_7',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_8',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='contact_number_stu_9',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_10',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_2',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_3',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_4',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_5',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_6',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_7',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_8',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department_stu_9',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu10',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu4',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu5',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu6',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu7',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu8',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email_stu9',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='student_9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_10',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='vtu_number_9',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VTU Number'),
        ),
    ]
