# Generated by Django 5.2.5 on 2025-09-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_internshipapplication_contact_number_stu_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu10',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu2',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu3',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu4',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu5',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu6',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu7',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu8',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='email_stu9',
        ),
    ]
