# Generated by Django 5.2.5 on 2025-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_remove_internshipapplication_email_stu10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='approval_message',
            field=models.TextField(blank=True, default='Your application is under review. We will notify you once a decision is made.', null=True, verbose_name='Message Regarding Approval Status'),
        ),
    ]
