# Generated by Django 5.2.5 on 2025-09-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_alter_internshipapplication_approval_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='approval_message',
            field=models.TextField(blank=True, default='Your application is under review. Please check back later.', null=True, verbose_name='Message Regarding Approval Status'),
        ),
    ]
