# Generated by Django 5.2.5 on 2025-09-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_alter_internshipapplication_approval_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='max_students_per_internship',
            field=models.PositiveIntegerField(default=10, verbose_name='Max Students per Internship'),
        ),
    ]
