# Generated by Django 5.2.5 on 2025-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_alter_sitesetting_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='SiteSettings',
            field=models.CharField(default='Site Settings', editable=False, max_length=100),
        ),
    ]
