# Generated by Django 5.2.5 on 2025-10-11 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_alter_sitesetting_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vtu_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(blank=True, choices=[('HOD', 'Head of Department'), ('Student', 'Student'), ('Faculty', 'Faculty')], max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
