# Generated by Django 5.2.5 on 2025-10-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_dept_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_member',
            name='year',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
