# Generated by Django 5.2.5 on 2025-10-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_dept_member_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Student1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student1_vtu', models.CharField(blank=True, max_length=20, null=True)),
                ('Student2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student2_vtu', models.CharField(blank=True, max_length=20, null=True)),
                ('Student3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student3_vtu', models.CharField(blank=True, max_length=20, null=True)),
                ('Student4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student4_vtu', models.CharField(blank=True, max_length=20, null=True)),
                ('Student5_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Student5_vtu', models.CharField(blank=True, max_length=20, null=True)),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_oneliner', models.CharField(blank=True, max_length=300, null=True)),
                ('project_abstract', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
