# Generated by Django 5.2.5 on 2025-10-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0016_alter_batch_batch_number_guide_batch_guide_assigned_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='applied_company',
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
        migrations.DeleteModel(
            name='StudentReport',
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message1_color',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='green', max_length=10, verbose_name='Message 1 Color'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message2_color',
            field=models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='orange', max_length=10, verbose_name='Message 2 Color'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
